// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_128x160

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Main_container;
extern lv_obj_t *ui_Main_Menu;
extern lv_obj_t *ui_XLR_menu_button;
extern lv_obj_t *ui_XLR_label;
extern lv_obj_t *ui_RJ45_menu_button;
extern lv_obj_t *ui_RJ45_label;
extern lv_obj_t *ui_Settings_menu_button;
extern lv_obj_t *ui_Settings_label;
extern lv_obj_t *ui_XLR_test_options_container;
extern lv_obj_t *ui_XLR_test1_button;
extern lv_obj_t *ui_XLR_test1_lable;
extern lv_obj_t *ui_XLR_test2_button;
extern lv_obj_t *ui_XLR_test2_lable;
extern lv_obj_t *ui_XLR_test3_button;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_XLR_info_lable;
extern lv_obj_t *ui_XLR_test1;
extern lv_obj_t *ui_Testing1_lable;
extern lv_obj_t *ui_XLR_test2;
extern lv_obj_t *ui_testing2_lable;
extern lv_obj_t *ui_XLR_test3;
extern lv_obj_t *ui_testing3_lable;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

