// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_128x160

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Main_container;
extern lv_obj_t *ui_Main_Menu;
extern lv_obj_t *ui_XLR_menu_button;
extern lv_obj_t *ui_XLR_label;
extern lv_obj_t *ui_RJ45_menu_button;
extern lv_obj_t *ui_RJ45_label;
extern lv_obj_t *ui_Settings_menu_button;
extern lv_obj_t *ui_Settings_label;
extern lv_obj_t *ui_XLR_test;
extern lv_obj_t *ui_XLR_testing_mode_lable;
extern lv_obj_t *ui_Pin1;
extern lv_obj_t *ui_Pin1GND;
extern lv_obj_t *ui_Pin1Result;
extern lv_obj_t *ui_Pin2;
extern lv_obj_t *ui_Pin2Dplus;
extern lv_obj_t *ui_Pin2Result;
extern lv_obj_t *ui_Pin3;
extern lv_obj_t *ui_Pin3Dminus;
extern lv_obj_t *ui_Pin3Result;
extern lv_obj_t *ui_Cable_Quality;
extern lv_obj_t *ui_Cable_Quality_lable;
extern lv_obj_t *ui_RJ45_test;
extern lv_obj_t *ui_RJ45_testing_lable;
extern lv_obj_t *ui_RJ45_side_A;
extern lv_obj_t *ui_side_AS;
extern lv_obj_t *ui_side_A1;
extern lv_obj_t *ui_side_A2;
extern lv_obj_t *ui_side_A3;
extern lv_obj_t *ui_side_A4;
extern lv_obj_t *ui_side_A5;
extern lv_obj_t *ui_side_A6;
extern lv_obj_t *ui_side_A7;
extern lv_obj_t *ui_side_A8;
extern lv_obj_t *ui_RJ45_side_B;
extern lv_obj_t *ui_side_BS;
extern lv_obj_t *ui_side_B1;
extern lv_obj_t *ui_side_B2;
extern lv_obj_t *ui_side_B3;
extern lv_obj_t *ui_side_B4;
extern lv_obj_t *ui_side_B5;
extern lv_obj_t *ui_side_B6;
extern lv_obj_t *ui_side_B7;
extern lv_obj_t *ui_side_B8;
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_Settings_menu_scrollable;
extern lv_obj_t *ui_Settings_XLR_test_container;
extern lv_obj_t *ui_XLR_test_mode_lable;
extern lv_obj_t *ui_XLR_test_mode_slider;
extern lv_obj_t *ui_XLR_mode_Female_lable;
extern lv_obj_t *ui_XLR_mode_Male_lable;
extern lv_obj_t *ui_XLR_mode_Normal_lable;
extern lv_obj_t *ui_Settings_RJ45_test_container;
extern lv_obj_t *ui_Settings_Volume_container;
extern lv_obj_t *ui_Volume_slider;
extern lv_obj_t *ui_Volume_lable;
extern lv_obj_t *ui_Settings_Brightness_container;
extern lv_obj_t *ui_Brightness_slider;
extern lv_obj_t *ui_Brightness_lable;
extern lv_obj_t *ui_Settings_vibration_container;
extern lv_obj_t *ui_Vibration_checkbox;
extern lv_obj_t *ui_Settings_Back_button;
extern lv_obj_t *ui_Back_button;
extern lv_obj_t *ui_BACK_lable;
extern lv_obj_t *ui_ScrollTrack;
extern lv_obj_t *ui_ScrollThumb;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

