// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_128x160

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Main_container;
extern lv_obj_t *ui_Main_Menu;
extern void ui_event_XLR_menu_button( lv_event_t * e);
extern lv_obj_t *ui_XLR_menu_button;
extern lv_obj_t *ui_XLR_label;
extern lv_obj_t *ui_RJ45_menu_button;
extern lv_obj_t *ui_RJ45_label;
extern lv_obj_t *ui_Settings_menu_button;
extern lv_obj_t *ui_Settings_label;
extern void ui_event_XLR_test_options_container( lv_event_t * e);
extern lv_obj_t *ui_XLR_test_options_container;
extern void ui_event_XLR_test1_button( lv_event_t * e);
extern lv_obj_t *ui_XLR_test1_button;
extern lv_obj_t *ui_XLR_test1_lable;
extern void ui_event_XLR_test2_button( lv_event_t * e);
extern lv_obj_t *ui_XLR_test2_button;
extern lv_obj_t *ui_XLR_test2_lable;
extern lv_obj_t *ui_XLR_info_lable;
extern void ui_event_XLR_test1( lv_event_t * e);
extern lv_obj_t *ui_XLR_test1;
extern lv_obj_t *ui_Testing1_lable;
extern lv_obj_t *ui_XLR_test2_menu;
extern void ui_event_XLR_test2_option( lv_event_t * e);
extern lv_obj_t *ui_XLR_test2_option;
extern void ui_event_test2_male_pluged_button( lv_event_t * e);
extern lv_obj_t *ui_test2_male_pluged_button;
extern lv_obj_t *ui_Male_pluged_lable;
extern void ui_event_test2_female_pluged_button( lv_event_t * e);
extern lv_obj_t *ui_test2_female_pluged_button;
extern lv_obj_t *ui_Female_pluged_lable;
extern void ui_event_XLR_test2_male( lv_event_t * e);
extern lv_obj_t *ui_XLR_test2_male;
extern lv_obj_t *ui_XLR_testing2_male_lable;
extern void ui_event_XLR_test2_female( lv_event_t * e);
extern lv_obj_t *ui_XLR_test2_female;
extern lv_obj_t *ui_XLR_testing2_female_lable;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

